var bingoList = [
    [
    {"name": "敵を盾だけで倒す", "en": "Defeat an enemy using only Shields", "types": [ "Combat"] },     
    {"name": "古びた下履き", "en": "Archaic Legwear", "types": [ "Armor", "GSI"] },
    {"name": "古びた防寒着", "en": "Archaic Warm Greaves", "types": [ "Armor", "GSI"] },
    {"name": "古びたトーガ", "en": "Archaic Tunic", "types": [ "Armor", "GSI"] },
    {"name": "ルミーからルピーを手に入れる", "en": "Get a Rupee from a Blupee", "types": [ "Caves"] },   
    ], [
    {"name": "モドレコだけで敵を倒す", "en": "Defeat an enemy using only Recall", "types": [ "Combat"] },
    {"name": "ウツシエ", "en": "Obtain the Camera", "types": [ "SideAdventures", "LookoutLanding"] },
    {"name": "ハイラル平原鳥望台を起動", "en": "Hyrule Field Tower", "types": [ "Towers", "HyruleField"] },
    {"name": "矢50本", "en": "Collect 50 arrows", "types": [ "Weapons"] },
    {"name": "懐かしい柄の生地", "en": "Nostalgic Fabric", "types": [ "Fabrics", "HyruleField"] },
    {"name": "山盛焼きキノコを作る", "en": "Cook Copious Mushroom Skewers", "types": [ "Recipes"] },
    {"name": "山盛串焼き魚を作る", "en": "Cook Copious Seafood Skewers", "types": [ "Recipes"] },
    {"name": "ハイリアの盾", "en": "Hylian Shield", "types": [ "Weapons"] },
    {"name": "戦闘中に肉で敵を気をそらす", "en": "Distract an enemy with meat during combat", "types": [ "Combat"] },
    {"name": "ミニチャレンジ:招かれざる者", "en": "An Uninvited Guest SQ", "types": [ "SideQuests", "Combat", "Stables", "SahasraSlope"] },
    ], [
    {"name": "ウィズローブ討伐 (どの種でも可)", "en": "Defeat a Wizzrobe of any kind", "types": [ "Combat"] },
    {"name": "隊長ゴーレム討伐 (どの種でも可)", "en": "Defeat a Captain Construct of any kind", "types": [ "Combat"] },
    {"name": "賢者の遺志1つ", "en": "Obtain 1 Sage's Will", "types": [ "Sky"] },
    {"name": "黄昏の弓", "en": "Obtain Dusk Bow", "types": [ "Weapons"] },
    {"name": "コッコでゲームオーバーになる", "en": "Game Over from Cuccos", "types": [ "GameOver"] },
    {"name": "瘴気でゲームオーバーになる", "en": "Game Over from Gloom", "types": [ "GameOver"] },
    {"name": "ゆでタマゴを作る", "en": "Make a Hard-Boiled Egg", "types": [ "Recipes"] },
    {"name": "レベル2の滑らず薬を作る", "en": "Cook Level 2 Sticky Elixir", "types": [ "Recipes"] },
    {"name": "レベル2のアカリ薬を作る", "en": "Cook Level 2 Bright Elixir", "types": [ "Recipes"] },
    {"name": "エピソードチャレンジ:ボックリンの困りごと", "en": "Hestu's Concerns SA", "types": [ "SideQuests", "Koroks", "Lindor'sBrow"] },
    {"name": "魔人像でポゥを交換", "en": "Exchange Poes with a Bargainer Statue", "types": [ "Depths"] },
    {"name": "ミニチャレンジ:憧れの荷馬車", "en": "Horse-Drawn Dreams SQ", "types": [ "SideQuests", "Stables", "Lindor'sBrow"] },
    ], [
    {"name": "エピソードチャレンジ:探して！マヨイの落とし物", "en": "The Hunt for Bubbul Gems! Side Adventure", "types": [ "Caves", "Koltin", "SideQuests"] },
    {"name": "イワロック討伐 (どの種でも可)", "en": "Defeat a Talus of any kind", "types": [ "Combat", "Talus"] },
    {"name": "ケムリダケを使って不意打ちする", "en": "Sneakstrike an enemy in a Puffshroom cloud", "types": [ "Combat", "Depths"] },
    {"name": "カルーガ峠鳥望台を起動", "en": "Rospro Pass Tower", "types": [ "Towers", "RosproPass", "Hebra"] },
    {"name": "ゲルドキャニオン鳥望台を起動", "en": "Gerudo Canyon Tower", "types": [ "Towers", "GerudoCanyon", "Gerudo"] },
    {"name": "ポプラー高地鳥望台を起動", "en": "Popla Foothills Tower", "types": [ "Towers", "PoplaFoothills"] },
    {"name": "ラベラ湿地帯鳥望台を起動", "en": "Rabella Wetlands Tower", "types": [ "Towers", "RabellaWetlands"] },
    {"name": "監視砦エリアのコログのミ5つ", "en": "5 Lookout Landing Korok Seeds", "types": [ "LookoutLanding", "Koroks"] },
    {"name": "落雷でゲームオーバー", "en": "Game Over from a Lightning Strike", "types": [ "GameOver"] },
    {"name": "ハイラル王家の生地", "en": "Royal Hyrulean Fabric", "types": [ "Fabrics", "LookoutLanding"] },
    {"name": "馬神様の生地", "en": "Horse-God Fabric", "types": [ "Fabrics", "Stables"] },
    {"name": "トリ肉オイル揚げを作る", "en": "Cook Deep-Fried Drumstick", "types": [ "Recipes"] },
    {"name": "古代の刃で敵を倒す", "en": "Defeat an enemy using an Ancient Blade", "types": [ "Combat"] },
    {"name": "スタルホースに乗る", "en": "Ride a Stalhorse", "types": [ "Depths"] },
    {"name": "朽ちていない武器", "en": "Retain a Pristine Weapon", "types": [ "Depths", "Weapons"] },
    {"name": "水や砂の渦に落ちる", "en": "Fall through any sand or water whirlpool", "types": [ "GerudoCanyon", "UplandZorana"] },
    {"name": "イチカラ村でスクラビルドを解除する", "en": "Unfuse an equipment in Tarrey Town", "types": [ "UlriMountain"] },
    {"name": "近衛武器の特殊効果を使う", "en": "Use a Royal Guard’s weapon at low durability", "types": [ "Combat"] },
    {"name": "ミニゲーム:ぬいぐるみ回収", "en": "Complete 1 Sand Seal Plushie Minigame", "types": [ "Minigames"] },
    {"name": "ミニゲーム:ボール運び", "en": "300+ meters in the Ultra Ball Haul Minigame", "types": [ "Minigames", "Lindor'sBrow"] },
    {"name": "ほこらチャレンジ:水から生まれし鍵", "en": "Keys Born of Water Shrine Quest", "types": [ "Shrines", "PoplaFoothills"] },
    {"name": "ほこらチャレンジ:槍投げの言い伝え", "en": "Legend of the Soaring Spear Shrine Quest", "types": [ "Shrines", "PoplaFoothills"] },
    {"name": "ほこらチャレンジ:黒く染め上げて", "en": "Dyeing to Find It Shrine Quest", "types": [ "Shrines", "SahasraSlope"] },
    ], [
    {"name": "3体同時にコンラン花で混乱させる", "en": "Confuse 3 enemies with one Muddle Bud", "types": [ "Combat"] },
    {"name": "ヒノックス討伐 (どの種でも可)", "en": "Defeat a Hinox of any kind", "types": [ "Combat"] },
    {"name": "ブロックゴーレム討伐 (どの種でも可)", "en": "Defeat a Flux Construct of any kind", "types": [ "Combat", "Sky"] },
    {"name": "ツツキキ雪原鳥望台を起動", "en": "Pikida Stonegrove Tower", "types": [ "Towers", "PikidaStonegrove", "Hebra"] },
    {"name": "ゾラ台地鳥望台を起動", "en": "Upland Zorana Tower", "types": [ "Towers", "UplandZorana"] },
    {"name": "ハイラル平原エリアのコログのミ5個", "en": "5 Hyrule Field Korok Seeds", "types": [ "HyruleField", "Koroks"] },
    {"name": "ユノシタに井戸5つを報告", "en": "Report 5 Wells to Fera", "types": [ "Stables"] },
    {"name": "新式・英傑の服", "en": "Champion’s Leathers", "types": [ "Armor"] },
    {"name": "ミニゲーム:ゴング鳴らし", "en": "Complete Test of Strength Minigame", "types": [ "Minigames"] },
    {"name": "エピソードチャレンジ:トコユの大事な手紙", "en": "A Letter to Koyin SA", "types": [ "SideAdventures", "MountLanayru"] },
    {"name": "ミニチャレンジ:コッコの道しるべ", "en": "Follow the Cuccos SQ", "types": [ "SideQuests", "SahasraSlope"] },
    {"name": "ミニチャレンジ:情熱デコレーション", "en": "Decorate with Passion SQ", "types": [ "SideQuests", "GerudoCanyon"] },
    {"name": "チュチュゼリー全種", "en": "Obtain All 4 Chuchu Jellies", "types": [ "Combat"] },
    {"name": "秘湯を発見する", "en": "Discover a Secret Hot Spring", "types": [ "RosproPass"] },
    {"name": "古びた髪留め", "en": "Well-Worn Hair Band", "types": [ "Armor", "MountLanayru"] },
    {"name": "テリーにカブトムシをあげる", "en": "Give Beedle a Beetle", "types": [ "Stables"] },
    {"name": "ほこらチャレンジ:巨大な馬を連れて", "en": "Ride the Giant Horse Shrine Quest", "types": [ "Shrines", "PoplaFoothills"] },
    {"name": "染められない装備を染めようとする", "en": "Attempt to dye undyable armor", "types": [ "Armor", "MountLanayru"] },
    ], [
    {"name": "鎧を着た敵を倒す", "en": "Defeat an Armored Enemy", "types": [ "Combat"] },
    {"name": "デクガーマにバクダン花を食べさせる", "en": "Feed a Bomb to a Frox", "types": [ "Combat", "Depths"] },
    {"name": "ボスボコブリン討伐 (どの種でも可)", "en": "Defeat a Boss Bokoblin", "types": [ "Combat"] },
    {"name": "ドンゴからアイテムをもらう", "en": "Obtain an item from a Dondon", "types": [ "PoplaFoothills"] },
    {"name": "ブループリント", "en": "Obtain Autobuild", "types": [ "Depths"] },
    {"name": "ラブラー山鳥望を起動", "en": "Lindor's Brow Tower", "types": [ "Towers", "Lindor'sBrow"] },
    {"name": "サハスーラ平原鳥望台を起動", "en": "Sahasra Slope Tower", "types": [ "Towers", "SahasraSlope", "Caves"] },
    {"name": "オルディン峡谷鳥望台を起動", "en": "Eldin Canyon Tower", "types": [ "Towers", "EldinCanyon"] },
    {"name": "ウルリ山鳥望台を起動", "en": "Ulri Mountain Tower", "types": [ "Towers", "UlriMountain"] },
    {"name": "監視砦エリアの祠4つ", "en": "4 Lookout Landing Shrines", "types": [ "LookoutLanding", "Shrines"] },
    {"name": "ハイラル平原エリアの祠4つ", "en": "4 Hyrule Field Shrines", "types": [ "HyruleField", "Shrines"] },
    {"name": "レベル3の滑らず薬を作る", "en": "Cook Level 3 Sticky Elixir", "types": [ "Recipes"] },
    {"name": "レベル3のアカリ薬を作る", "en": "Cook Level 3 Bright Elixir", "types": [ "Recipes"] },
    {"name": "祝福の祠4つ", "en": "4 Blessing Shrines", "types": [ "Shrines", "Travel"] },
    {"name": "デクガーマと自撮り", "en": "Take a Selfie with a Frox", "types": [ "Camera", "Depths", "Frox"] },
    {"name": "ミニゲーム:荷運び馬レース", "en": "Complete the Horse Towing Minigame", "types": [ "Minigames", "PoplaFoothills"] },
    {"name": "エピソードチャレンジ:新名物で村おこし！", "en": "A New Signature Food SA", "types": [ "SideAdventures", "MountLanayru"] },
    {"name": "ミニチャレンジ:タンブル・ウィードの大掃除", "en": "The Great Tumbleweed Purge SQ", "types": [ "SideQuests", "GerudoCanyon"] },
    {"name": "犬の宝箱3つ", "en": "3 Dog Treasure Chests", "types": [ "Stables", "Travel"] },
    {"name": "ほこらチャレンジ:天高き泉と光輪の伝承", "en": "The High Spring and the Light Rings Shrine Quest", "types": [ "Shrines", "MountLanayru"] },
    {"name": "2つの桜の木に果物を備える", "en": "Offer Fruit at 2 Cherry Blossom Trees", "types": [ "CherryBlossom", "Travel"] },
    {"name": "ダークボディ", "en": "Dark Tunic", "types": [ "Depths", "Armor"] },
    ], [
    {"name": "カガヤキの実でギブドを倒す", "en": "Defeat a Gibdo using Dazzle Fruit", "types": [ "Combat"] },
    {"name": "ライネル討伐 (どの種でも可)", "en": "Defeat a Lynel of any kind", "types": [ "Combat"] },
    {"name": "イエロック討伐 (どの種でも可)", "en": "Defeat a Battle Talus", "types": [ "Combat", "Talus"] },
    {"name": "デクガーマ討伐 (どの種でも可)", "en": "Defeat a Frox of any kind", "types": [ "Combat", "Depths"] },
    {"name": "フィールドボス2体討伐", "en": "Defeat 2 Minibosses", "types": [ "Combat"] },
    {"name": "古びたマップ3つ", "en": "Obtain 3 Old Maps", "types": [ "Sky"] },
    {"name": "ラネール山鳥望台を起動", "en": "Mount Lanayru Tower", "types": [ "Towers", "MountLanayru"] },
    {"name": "ドイブラン遺跡鳥望台を起動", "en": "Thyphlo Ruins Tower", "types": [ "Towers", "ThyphloRuins"] },
    {"name": "カルーガ峠エリアのコログのミ5個", "en": "5 Rospro Pass Korok Seeds", "types": [ "RosproPass", "Koroks"] },
    {"name": "ゲルドキャニオンエリアのコログのミ5個", "en": "5 Gerudo Canyon Korok Seeds", "types": [ "GerudoCanyon", "Koroks"] },
    {"name": "ポプラー高地エリアのコログのミ5個", "en": "5 Popla Foothills Korok Seeds", "types": [ "PoplaFoothills", "Koroks"] },
    {"name": "ラベラ湿地帯エリアのコログのミ5個", "en": "5 Rabella Wetlands Korok Seeds", "types": [ "RabellaWetlands", "Koroks"] },
    {"name": "5種類の解き方のコログ", "en": "Complete 5 Unique Types of Koroks", "types": [ "Koroks"] },
    {"name": "カバンダを5回助ける", "en": "Help Addison 5 times", "types": [ "Addison", "Travel"] },
    {"name": "コーガを一回倒す", "en": "Defeat Kohga Once", "types": [ "Combat", "Depths"] },
    {"name": "ほこらチャレンジ3つ", "en": "3 Shrine Quests", "types": [ "Shrines"] },
    {"name": "イーガ団の乗り物を奪う", "en": "Steal a Yiga's Ride", "types": [ "Combat", "Depths", "Yiga"] },
    {"name": "グライドスーツ", "en": "Glide Shirt", "types": [ "Sky", "Armor"] },
    {"name": "犬と自撮り", "en": "Take a selfie with a dog", "types": [ "Camera", "Stables"] },
    {"name": "コーガと自撮り", "en": "Take a Selfie with Master Kohga", "types": [ "Camera", "Depths", "Yiga"] },
    {"name": "ミニゲーム:ぬいぐるみ回収を2つ", "en": "Complete 2 Sand Seal Plushie Minigames", "types": [ "Minigames", "Travel"] },
    {"name": "エピソードチャレンジ:迷えるシロヤギの受難", "en": "White Goats Gone Missing SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables"] },
    {"name": "エピソードチャレンジ:不気味な声", "en": "An Eerie Voice SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "PoplaFoothills", ""] },       
    {"name": "エピソードチャレンジ:クサヨシの秘密", "en": "Reede's Secret SA", "types": [ "SideAdventures", "MountLanayru"] },
    {"name": "エピソードチャレンジ:サゴノの秘密", "en": "Cece's Secret SA", "types": [ "SideAdventures", "MountLanayru"] },
    {"name": "ミニチャレンジ:ゲンコの手料理", "en": "Genli's Home Cooking SQ", "types": [ "SideQuests", "RosproPass"] },
    {"name": "ミニチャレンジ:扉を開けて", "en": "Open the Door SQ", "types": [ "SideQuests", "RosproPass"] },
    {"name": "ミニチャレンジ:病は瘴気から", "en": "Gloom-Borne Illness SQ", "types": [ "SideQuests", "SahasraSlope"] },
    {"name": "ミニチャレンジ:SOSの手紙", "en": "A Bottle Cry for Help SQ", "types": [ "SideQuests"] },
    ], [
    {"name": "マヨイの落とし物5つ", "en": "5 Bubbul Gems", "types": [ "Caves", "Koltin"] },
    {"name": "隊長ゴーレム(上等)を倒す", "en": "Defeat a Captain Construct III", "types": [ "Combat"] },
    {"name": "祠8つ", "en": "8 Shrines", "types": [ "Shrines"] },
    {"name": "ツツキキ雪原エリアのコログのミ5個", "en": "5 Pikida Stonegrove Korok Seeds", "types": [ "PikidaStonegrove", "Koroks"] },
    {"name": "ゾラ台地エリアのコログのミ5個", "en": "5 Upland Zorana Korok Seeds", "types": [ "UplandZorana", "Koroks"] },
    {"name": "疲れコログのミ5つ", "en": "5 Backpack Korok Seeds", "types": [ "Koroks"] },
    {"name": "カルーガ峠エリアの祠4つ", "en": "4 Rospro Pass Shrines", "types": [ "RosproPass", "Shrines"] },
    {"name": "ゲルドキャニオンエリアの祠4つ", "en": "4 Gerudo Canyon Shrines", "types": [ "GerudoCanyon", "Shrines"] },
    {"name": "ポプラー高原エリアの祠4つ", "en": "4 Popla Foothills Shrines", "types": [ "PoplaFoothills", "Shrines"] },
    {"name": "ラベラ湿地帯エリアの祠4つ", "en": "4 Rabella Wetlands Shrines", "types": [ "RabellaWetlands", "Shrines"] },
    {"name": "ダイビング中に空中でゲームオーバー", "en": "Game Over while skydiving (in mid-air)", "types": [ "GameOver"] },
    {"name": "7ポイントでマーロンベッドを使う", "en": "Sleep in a Malanya Bed (7 Pony Points)", "types": [ "Stables", "Travel"] },
    {"name": "ミニチャレンジ/エピソードチャレンジ5つ", "en": "Complete 5 Side Quests/Adventures", "types": [ "SideQuests"] },
    {"name": "敵のキャンプの宝箱3つ", "en": "Open 3 Enemy Camp Chests", "types": [ "Combat", "Travel"] },
    {"name": "エピソードチャレンジ:コルテンの行方", "en": "The Search for Koltin SA", "types": [ "Koltin", "EldinCanyon"] },
    {"name": "エピソードチャレンジ:あなたサゴノ派？クサヨシ派？", "en": "Team Cece or Team Reede? SA", "types": [ "SideAdventures", "MountLanayru"] },
    {"name": "ミニチャレンジ:ラムダのお宝さがし", "en": "Misko's Cave of Chests SQ", "types": [ "SideQuests", "Stables"] },
    {"name": "ミニチャレンジ:教えてティーチャー！", "en": "Teach Me a Lesson I SQ", "types": [ "SideQuests", "Camera"] },
    {"name": "ミニチャレンジ:氷なき氷室", "en": "The Iceless Icehouse SQ", "types": [ "SideQuests", "Gerudo"] },
    {"name": "近衛兵装備一式", "en": "Full Royal Guard Set", "types": [ "Armor", "LookoutLanding"] },
    ], [
    {"name": "古びたマップとその宝箱を開ける", "en": "Find an Old Map and its Treasure", "types": [ "Sky", "Depths"] },
    {"name": "ゲルド高地鳥望台を起動", "en": "Gerudo Highlands Tower", "types": [ "Towers", "GerudoHighlands", "Gerudo"] },
    {"name": "ラブラー山エリアのコログのミ5個", "en": "5 Lindor's Brow Korok Seeds", "types": [ "Lindor'sBrow", "Koroks"] },
    {"name": "サハスーラ平原エリアのコログのミ5個", "en": "5 Sahasra Slope Korok Seeds", "types": [ "SahasraSlope", "Koroks"] },
    {"name": "オルディン峡谷エリアのコログのミ5個", "en": "5 Eldin Canyon Korok Seeds", "types": [ "EldinCanyon", "Koroks"] },
    {"name": "ウルリ山エリアのコログのミ5個", "en": "5 Ulri Mountain Korok Seeds", "types": [ "UlriMountain", "Koroks"] },
    {"name": "設計図5つ", "en": "5 Autobuild Schematics", "types": [ "Depths", "Travel"] },
    {"name": "ゲルドの牢屋に入る", "en": "Stand in Gerudo Jail", "types": [ "Gerudo"] },
    {"name": "地底からトーレルーフで地上に出る", "en": "Ascend out of the Depths", "types": [ "Depths"] },
    {"name": "本丸の玉座で自撮り", "en": "Take a Selfie on the Throne in Sanctum", "types": [ "Camera", "LookoutLanding"] },
    {"name": "戦闘中にバナナでイーガ団の気をそらす", "en": "Distract a Yiga with a banana during combat", "types": [ "Combat", "Yiga"] },
    {"name": "エピソードチャレンジ:ハイラル平原に平和を！", "en": "Bring Peace to Hyrule Field! SA", "types": [ "Combat", "HyruleField"] },
    {"name": "エピソードチャレンジ:訪れぬ美食家", "en": "Gourmets Gone Missing SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "LookoutLanding", ""] 
    },
    {"name": "エピソードチャレンジ:怪物に乗った姫", "en": "The Beast and the Princess SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "PoplaFoothills", ""] },
    {"name": "エピソードチャレンジ:消えた農具", "en": "The Missing Farm Tools SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "SahasraSlope", ""] }, 
    {"name": "ミニチャレンジ:肉には肉を！", "en": "Meat for Meat SQ", "types": [ "SideQuests"] },
    {"name": "メドーの止まり木から光線の頭で撃つ", "en": "Shoot a Beam Emitter from Vah Medoh's Perch", "types": [ "RosproPass"] },
    {"name": "地上のゾナウギア製造機を3つ使う", "en": "Use all 3 Device Dispensers on the Surface", "types": [ "HyruleField", "SahasraSlope", "UlriMountain"] },
    ], [
    {"name": "フィールドボス4体討伐", "en": "Defeat 4 Minibosses", "types": [ "Combat"] },
    {"name": "破魔の根5つ解放", "en": "Activate 5 Lightroots", "types": [ "Depths"] },
    {"name": "ラネール山エリアのコログのミ5個", "en": "5 Mount Lanayru Korok Seeds", "types": [ "MountLanayru", "Koroks"] },
    {"name": "ドイブラン遺跡エリアのコログのミ5個", "en": "5 Thyphlo Ruins Korok Seeds", "types": [ "ThyphloRuins", "Koroks"] },
    {"name": "妖精を4つ消費", "en": "Use 4 Fairies", "types": [ "Fairies"] },
    {"name": "ツツキキ雪原エリアの祠4つ", "en": "4 Pikida Stonegrove Shrines", "types": [ "PikidaStonegrove", "Shrines"] },
    {"name": "ゾラ台地エリアの祠4つ", "en": "4 Upland Zorana Shrines", "types": [ "UplandZorana", "Shrines"] },
    {"name": "空の祠8つ", "en": "8 Shrines in the Sky", "types": [ "Sky", "Shrines"] },
    {"name": "ファントムガノン討伐", "en": "Defeat a Phantom Ganon", "types": [ "Combat", "PhantomGanon"] },
    {"name": "ナッツケーキを作る", "en": "Cook Nutcake", "types": [ "Recipes"] },
    {"name": "海賊船で自撮り", "en": "Take a Selfie on a Pirate Ship", "types": [ "Camera"] },
    {"name": "エピソードチャレンジ:ハテールに平和を！", "en": "Bring Peace to Necluda! SA", "types": [ "Combat", "SahasraSlope"] },
    {"name": "エピソードチャレンジ:ゼルダが愛した金色の馬", "en": "Zelda's Golden Horse SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "PikidaStonegrove", ""] },
    {"name": "エピソードチャレンジ:コッコ様の言う通り", "en": "The All-Clucking Cucco SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "UlriMountain", "Combat"] },
    {"name": "エピソードチャレンジ:ゼルダ姫誘拐事件！？", "en": "Princess Zelda Kidnapped?! SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "SahasraSlope", "Combat"] },
    {"name": "エピソードチャレンジ:封じられた井戸", "en": "The Blocked Well SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "GerudoCanyon", "Combat"] },
    {"name": "鐘を鳴らすコログ3つ", "en": "All 3 Ring the Bell Koroks", "types": [ "Koroks", "Travel"] },
    {"name": "ミニチャレンジ:岩トロケの湯", "en": "Simmerstone Springs SQ", "types": [ "SideQuests"] },
    {"name": "ミニチャレンジ:ゲルドキャニオンの遭難者", "en": "Disaster in Gerudo Canyon SQ", "types": [ "SideQuests", "GerudoCanyon"] },
    {"name": "チューリの弓を取り戻す", "en": "Recover Tulin's Bow", "types": [ "Temples", "Combat"] },
    {"name": "ユノシタに井戸10つを報告", "en": "Report 10 Wells to Fera", "types": [ "LookoutLanding"] },
    {"name": "ラムダの財宝3つ", "en": "3 Misko's Treasures", "types": [ "Armor", "Caves"] },
    ], [
    {"name": "ブロックゴーレム(上等)討伐 ", "en": "Defeat a Flux Construct III", "types": [ "Combat"] },
    {"name": "ほこらチャレンジ5つ", "en": "5 Shrine Quests", "types": [ "Shrines"] },
    {"name": "マモノにぎりを作る", "en": "Cook Monster Rice Balls", "types": [ "Recipes"] },
    {"name": "ゾナウギア10種", "en": "Retain 10 Unique Zonai Devices", "types": [ "Sky"] },
    {"name": "ヒメイダ山の溶岩滝を発見する", "en": "Discover Meda Lavafalls", "types": [ "Lavafalls", "MountLanayru"] },
    {"name": "ミニチャレンジ:コッコ捕獲大作戦", "en": "Feathered Fugitives SQ", "types": [ "SideQuests", "Stables", "HyruleField"] },
    {"name": "グライドマスク", "en": "Glide Mask", "types": [ "Sky", "Armor"] },
    {"name": "グリオークと自撮り", "en": "Take a Selfie with a Gleeok", "types": [ "Camera", "Gleeok"] },
    {"name": "エピソードチャレンジ:僕だけの魔物コレクション", "en": "A Monsterous Collection I SA", "types": [ "Koltin", "Camera"] },
    {"name": "エピソードチャレンジ:オルディンに平和を！", "en": "Bring Peace to Eldin! SA", "types": [ "Combat", "EldinCanyon"] },
    {"name": "エピソードチャレンジ:アッカレに平和を！", "en": "Bring Peace to Akkala! SA", "types": [ "Combat", "UlriMountain"] },
    {"name": "エピソードチャレンジ:フィローネに平和を！", "en": "Bring Peace to Faron! SA", "types": [ "Combat", "PoplaFoothills"] },
    {"name": "エピソードチャレンジ:いざなう女", "en": "The Beckoning Woman SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "HyruleField", ""] },     
    {"name": "ミニチャレンジ:太古のロマンをめぐる旅", "en": "A Trip through History SQ", "types": [ "SideQuests", "SahasraSlope"] },
    {"name": "ユン坊を倒す", "en": "Defeat Yunobo", "types": [ "Temples", "Combat"] },
    ], [
    {"name": "馬を強化", "en": "Upgrade A Horse", "types": [ "Stables"] },
    {"name": "祠12つ", "en": "12 Shrines", "types": [ "Shrines"] },
    {"name": "龍の泪3つ", "en": "Collect 3 Dragon Tear Memories", "types": [ "Lindor'sBrow", "Tears"] },
    {"name": "エピソードチャレンジ:ウィッダの独り立ち", "en": "Mattison's Independence SA", "types": [ "SideAdventures", "UlriMountain"] },
    {"name": "コログのミ15個", "en": "15 Korok Seeds", "types": [ "Koroks"] },
    {"name": "ゲルド高地エリアのコログのミ5個", "en": "5 Gerudo Highlands Korok Seeds", "types": [ "GerudoHighlands", "Koroks"] },
    {"name": "ラブラー山エリアの祠4つ", "en": "4 Lindor's Brow Shrines", "types": [ "Lindor'sBrow", "Shrines"] },
    {"name": "サハスーラ平原エリアの祠4つ", "en": "4 Sahasra Slope Shrines", "types": [ "SahasraSlope", "Shrines"] },
    {"name": "オルディン峡谷エリアの祠4つ", "en": "4 Eldin Canyon Shrines", "types": [ "EldinCanyon", "Shrines"] },
    {"name": "ウルリ山エリアの祠4つ", "en": "4 Ulri Mountain Shrines", "types": [ "UlriMountain", "Shrines"] },
    {"name": "トマトピザを作る", "en": "Cook Hylian Tomato Pizza", "types": [ "Recipes", "MountLanayru"] },
    {"name": "一身の戦いの祠4つ", "en": "4 Proving Ground Shrines", "types": [ "Shrines", "Travel"] },
    {"name": "暗闇の衣", "en": "Tunic of the Depths", "types": [ "Depths", "Armor"] },
    {"name": "グライドタイツ", "en": "Glide Tights", "types": [ "Sky", "Armor"] },
    {"name": "エピソードチャレンジ:ヘブラに平和を！", "en": "Bring Peace to Hebra! SA", "types": [ "Combat", "PikidaStonegrove"] },
    {"name": "ミニゲーム:盾サーフィン", "en": "Complete Shield Surfing Minigame", "types": [ "Minigames"] },
    {"name": "ミニチャレンジ:コハク買い取ります", "en": "Amber Dealer SQ", "types": [ "SideQuests"] },
    {"name": "ミニチャレンジ:オルディンの大化石", "en": "Eldin's Colossal Fossil SQ", "types": [ "SideQuests"] },
    {"name": "カラカラバザール防衛", "en": "Defend Kara Kara Bazaar", "types": [ "Temples", "Combat"] },
    {"name": "ヘドロライクを倒す", "en": "Defeat Sludge Like", "types": [ "Temples", "Combat"] },
    {"name": "ライクライクの石全種", "en": "Obtain All 4 Like Stones", "types": [ "Combat"] },
    {"name": "犬の宝箱6つ", "en": "6 Dog Treasure Chests", "types": [ "Stables", "Travel"] },
    ], [
    {"name": "スタルヒノックス討伐", "en": "Defeat a Stalnox", "types": [ "Combat"] },
    {"name": "エピソードチャレンジ:あらくれどもの巣くう村", "en": "Ruffian-Infested Village SA", "types": [ "Combat", "SideAdventures", "RabellaWetlands"] },
    {"name": "敵のキャンプの宝箱6つ", "en": "Open 6 Enemy Camp Chests", "types": [ "Combat", "Travel"] },
    {"name": "ゲルドシークレットクラブで何か買う", "en": "Buy a piece of armor from Gerudo Secret Club", "types": [ "Armor"] },
    {"name": "祠と破魔の根4ペア", "en": "4 Shrine + Lightroot Pairs", "types": [ "Shrines", "Depths"] },
    {"name": "スクラビルドで攻撃力50の武器を作る", "en": "Create a weapon with a base attack power of 50", "types": [ "Weapons"] },
    {"name": "龍と自撮り", "en": "Take a Selfie with a Dragon", "types": [ "Camera", "Sky"] },
    {"name": "エピソードチャレンジ:僕だけの魔物コレクション2", "en": "A Monsterous Collection II SA", "types": [ "Koltin", "Camera", "Caves"] },
    {"name": "ミニゲーム:ボール返し", "en": "15 points in the Ball Returning Minigame", "types": [ "Minigames", "Lindor'sBrow"] },
    {"name": "ミニゲーム:ぬいぐるみ回収3つ", "en": "Complete 3 Sand Seal Plushie Minigames", "types": [ "Minigames", "Travel"] },
    {"name": "エピソードチャレンジ:マイスイートプリンセス", "en": "For Our Princess! SA", "types": [ "SideAdventures", "Penn", "Lindor'sBrow", "Stables", "EldinCanyon", "Combat"] },
    {"name": "コログ族の生地", "en": "Korok Fabric", "types": [ "Fabrics", "Combat", "ThyphloRuins"] },
    {"name": "ミニチャレンジ:たむろう海賊", "en": "The Gathering Pirates SQ", "types": [ "SideQuests", "Stables", "Combat"] },
    ], [
    {"name": "モルドラジーク討伐", "en": "Defeat a Molduga", "types": [ "Combat", "Gerudo", "Molduga"] },
    {"name": "フィールドボス6体討伐", "en": "Defeat 6 Minibosses", "types": [ "Combat"] },
    {"name": "10種の解き方のコログ", "en": "Complete 10 Unique Types of Koroks", "types": [ "Koroks"] },
    {"name": "妖精4匹", "en": "Retain 4 Fairies", "types": [ "Fairies"] },
    {"name": "ラネール山エリアの祠4つ", "en": "4 Mount Lanayru Shrines", "types": [ "MountLanayru", "Shrines"] },
    {"name": "ドイブラン遺跡エリアの祠4つ", "en": "4 Thyphlo Ruins Shrines", "types": [ "ThyphloRuins", "Shrines"] },
    {"name": "カバンダを10回助ける", "en": "Help Addison 10 times", "types": [ "Addison", "Travel"] },
    {"name": "ヴァーイミーツヴォーイを作る", "en": "Cook Noble Pursuit", "types": [ "Recipes", "GerudoCanyon"] },
    {"name": "バッテリー6つ", "en": "6 Energy Wells", "types": [ "Depths"] },
    {"name": "エピソードチャレンジ:大妖精に捧げるセレナーデ", "en": "Serenade to a Great Fairy SA", "types": [ "EldinCanyon", "Stables", "SideAdventures"] },
    {"name": "エピソードチャレンジ:いざ村長選！", "en": "The Mayoral Election SA", "types": [ "SideAdventures", "MountLanayru"] },
    {"name": "ミニチャレンジ:取り残された作業員", "en": "The Abandoned Laborer SQ", "types": [ "SideQuests", "EldinCanyon"] },
    {"name": "4つの桜の木に果物を備える", "en": "Offer Fruit at 4 Cherry Blossom Trees", "types": [ "CherryBlossom", "Travel"] },
    {"name": "兵士装備一式", "en": "Full Soldier's Set", "types": [ "Armor", "LookoutLanding"] },
    ], [
    {"name": "エピソードチャレンジ:クチューラに捧げるセレナーデ", "en": "Serenade to Cotera SA", "types": [ "SahasraSlope", "Stables", "SideAdventures"] },
    {"name": "マヨイの落とし物10つ", "en": "10 Bubbul Gems", "types": [ "Caves", "Koltin"] },
    {"name": "8キャラクターの情報", "en": "Obtain 8 Character Profiles", "types": [ "Temples"] },
    {"name": "ミニチャレンジ:探せ！ 海賊のアジト", "en": "Seeking the Pirate Hideout SQ", "types": [ "SideQuests", "Combat", "RabellaWetlands"] },
    {"name": "ユノシタに井戸を15個報告", "en": "Report 15 Wells to Fera", "types": [ "Stables"] },
    {"name": "馬のタテガミの装飾をする", "en": "Restyle a Horse's Mane (16 Pony Points)", "types": [ "Stables", "Travel"] },
    {"name": "洞窟内の祠4つ", "en": "4 Shrines in Caves", "types": [ "Caves", "Shrines", "Combat"] },
    {"name": "3つ部屋のあるマイホームを作る", "en": "Build a Dream Home with 3 Rooms", "types": [ "SideQuests"] },
    ], [
    {"name": "エピソードチャレンジ:ミジャーに捧げるセレナーデ", "en": "Serenade to Mija SA (Hebra)", "types": [ "PikidaStonegrove", "Stables", "SideAdventures"] },       
    {"name": "エピソードチャレンジ:シーザに捧げるセレナーデ", "en": "Serenade to Kaysa SA (Outskirt)", "types": [ "HyruleField", "Stables", "SideAdventures"] },
    {"name": "祠16つ", "en": "16 Shrines", "types": [ "Shrines"] },
    {"name": "ほこらチャレンジ10つ", "en": "10 Shrine Quests", "types": [ "Shrines"] },
    {"name": "セージから生地を5つもらう", "en": "5 Fabrics from Sayge", "types": [ "Fabrics", "MountLanayru", "Camera"] },
    {"name": "マジン煮込みを作る", "en": "Cook Dark Stew", "types": [ "Recipes"] },
    {"name": "精霊の衣", "en": "Mystic Robes", "types": [ "Armor"] },
    {"name": "ゾナウギア15種", "en": "Retain 15 Unique Zonai Devices", "types": [ "Sky"] },
    {"name": "エピソードチャレンジ:僕だけの魔物コレクション3", "en": "A Monsterous Collection III SA", "types": [ "Koltin", "Camera", "Talus"] },
    {"name": "ミニチャレンジ:ヘブラの大化石", "en": "Hebra's Colossal Fossil SQ", "types": [ "SideQuests", "RosproPass"] },
    {"name": "ミニチャレンジ:洞窟の巨人三兄弟", "en": "Ousting the Giants SQ", "types": [ "SideQuests", "Combat", "PoplaFoothills"] },
    ], [
    {"name": "ガチロックとマグロックを討伐", "en": "Defeat a Frost and Igneo Talus", "types": [ "Combat", "Hebra", "EldinCanyon", "Talus"] },
    {"name": "青と黒のヒノックスを討伐", "en": "Defeat a Blue and Black Hinox", "types": [ "Combat"] },
    {"name": "コーガを2回倒す", "en": "Defeat Kohga Twice", "types": [ "Combat", "Depths"] },
    {"name": "ダイゴロン刀", "en": "Obtain Biggoron's Sword", "types": [ "Combat", "Depths", "Weapons"] },
    {"name": "夢見の勇者一式", "en": "Full Awakening Set", "types": [ "Armor", "HyruleField", "Lindor'sBrow"] },
    {"name": "ミニチャレンジ/エピソードチャレンジ10つ", "en": "Complete 10 Side Quests/Adventures", "types": [ "SideQuests"] },
    {"name": "ミンフラーの溶岩滝を発見する", "en": "Discover Goflam's Lavafalls", "types": [ "Lavafalls", "Hebra"] },
    {"name": "クムの溶岩滝を発見する", "en": "Discover Sturnida Lavafalls", "types": [ "Lavafalls", "Hebra"] },
    {"name": "ミニチャレンジ:行方不明のオーナー", "en": "The Missing Owner SQ", "types": [ "SideQuests", "Combat", "GerudoCanyon"] },
    ], [
    {"name": "鎧のライネル討伐", "en": "Defeat an Armored Lynel", "types": [ "Combat"] },
    {"name": "スナザラシに乗りながらモルドラジーク討伐", "en": "Defeat a Molduga while riding a Sand Seal", "types": [ "Combat", "GerudoCanyon", "Molduga"] },
    {"name": "火炎グリオーク討伐", "en": "Defeat a Flame Gleeok", "types": [ "Combat", "Gleeok"] },
    {"name": "破魔の根10つ解放", "en": "Activate 10 Lightroots", "types": [ "Depths"] },
    {"name": "龍の泪5つ", "en": "Collect 5 Dragon Tear Memories", "types": [ "Lindor'sBrow", "Tears"] },
    {"name": "ゲルド高地エリアの祠4つ", "en": "4 Gerudo Highlands Shrines", "types": [ "GerudoHighlands", "Shrines"] },
    {"name": "鬼神の大剣", "en": "Obtain Fierce Deity's Sword", "types": [ "Armor", "Weapons", "UlriMountain", "LookoutLanding", "EldinCanyon", ""] },
    {"name": "ゼッカワミの溶岩滝を発見する", "en": "Discover Sherfin's Lavafalls", "types": [ "Lavafalls", "Hebra"] },
    {"name": "エピソードチャレンジ:僕だけの魔物コレクション4", "en": "A Monsterous Collection IV SA", "types": [ "Koltin", "Camera", "Frox", "Depths"] },
    {"name": "ミニチャレンジ:大きなグルグル", "en": "Whirly Swirly Things SQ", "types": [ "SideQuests", "Camera", "ThyphloRuins", "Combat"] },
    {"name": "イーガ装備一式", "en": "The Yiga Set", "types": [ "Yiga", "Armor", "UlriMountain", "HyruleField", "ThyphloRuins", ""] },
    ], [
    {"name": "雷電グリオーク討伐", "en": "Defeat a Thunder Gleeok", "types": [ "Combat", "Gleeok"] },
    {"name": "地底の闘技場攻略", "en": "Complete a Depths Colosseum", "types": [ "Combat", "Depths"] },
    {"name": "瘴気の金棒", "en": "Obtain a Gloom Club", "types": [ "Combat", "PhantomGanon"] },
    {"name": "14キャラクターの情報", "en": "Obtain 14 Character Profiles", "types": [ "Temples"] },
    {"name": "ほこらチャレンジ15つ", "en": "15 Shrine Quests", "types": [ "Shrines"] },
    {"name": "スクラビルドで攻撃力90の武器を作る", "en": "Create a weapon with a base attack power of 90", "types": [ "Weapons", "Combat"] },
    ], [
    {"name": "設計図10つ", "en": "10 Autobuild Schematics", "types": [ "Depths", "Travel"] },
    {"name": "マヨイの落とし物15つ", "en": "15 Bubbul Gems", "types": [ "Caves", "Koltin"] },
    {"name": "氷雪グリオーク討伐", "en": "Defeat a Frost Gleeok", "types": [ "Combat", "Gleeok"] },
    {"name": "エピソードチャレンジ:ウオトリー村再建計画", "en": "Lurelin Village Restoration Project SA", "types": [ "SideAdventures", "RabellaWetlands"] },
    {"name": "ミニゲーム:イチカラリーの上級コース", "en": "Complete the Advanced Course in Tarrey Town", "types": [ "UlriMountain"] },
    {"name": "空の祠12つ", "en": "12 Shrines in the Sky", "types": [ "Sky", "Shrines"] },
    ], [
    {"name": "バッテリー9つ", "en": "9 Energy Wells", "types": [ "Depths"] },
    {"name": "カバンダを15回助ける", "en": "Help Addison 15 times", "types": [ "Addison", "Travel"] },
    {"name": "ミネルの仮面をゴーレム製造所へ届ける", "en": "Deliver Mineru’s Mask to the Construct Factory", "types": [ "Temples", "Depths", "Sky"] },
    {"name": "女神の白刃剣", "en": "Obtain White Sword of the Sky", "types": [ "SideQuests", "Weapons", "Sky"] },
    {"name": "ミニチャレンジ:ゲルドの大化石", "en": "Gerudo's Colossal Fossil SQ", "types": [ "SideQuests"] },
    {"name": "騎士のくらと手綱", "en": "Knight's Saddle & Bridle (23 Pony Points)", "types": [ "Stables", "Travel"] },
    ], [
    {"name": "賢者の遺志8つ", "en": "Obtain 8 Sage's Wills", "types": [ "Sky", "Travel"] },
    {"name": "異次元悪霊のすねあて", "en": "Obtain the Evil Spirit Chestpiece", "types": [ "Sky", "Depths", "Combat", "Labyrinth", "UlriMountain", ""] },
    {"name": "異次元悪霊の鎧", "en": "Obtain the Evil Spirit Greaves", "types": [ "Sky", "Depths", "Combat", "Labyrinth", "Hebra", ""] },
    {"name": "異次元悪霊の兜", "en": "Obtain the Evil Spirit Mask", "types": [ "Sky", "Depths", "Combat", "Labyrinth", "Gerudo", ""] },
    {"name": "ミニチャレンジ:ジャーブ台地の砦攻略", "en": "The Fort at Ja'Abu Ridge SQ", "types": [ "SideQuests", "Combat", "UplandZorana"] },
    {"name": "ミニチャレンジ:リト族の物々交換", "en": "Fish for Fletching SQ", "types": [ "SideQuests", "RosproPass"] },
    {"name": "セージから生地を10つもらう", "en": "10 Fabrics from Sayge", "types": [ "Fabrics", "MountLanayru", "Camera"] },
    {"name": "ゾナウギア25種", "en": "Retain 25 Unique Zonai Devices", "types": [ "Sky"] },
    {"name": "4人の賢者の末裔に会う", "en": "Talk to the 4 Sage Descendants", "types": [ "RosproPass", "EldinCanyon", "GerudoCanyon", "UplandZorana"] },
    ], [
    {"name": "盟約1つ入手", "en": "Obtain a Sage's Vow", "types": [ "Temples", "Combat"] },
    {"name": "ムジュラの仮面", "en": "Majora's Mask", "types": [ "Combat", "Depths", "Armor"] },
    {"name": "キンググリオーク討伐", "en": "Defeat a King Gleeok", "types": [ "Combat", "Gleeok"] },
    {"name": "地底の闘技場3つ攻略", "en": "Complete 3 Depths Colosseum", "types": [ "Combat", "Depths"] },
    {"name": "ミニチャレンジ:月下にたたずむゾーラ姫", "en": "The Moonlit Princess SQ", "types": [ "SideQuests", "Camera", "UplandZorana"] },
    {"name": "護雷の兜", "en": "Lightning Helm", "types": [ "Armor", "GerudoHighlands", "HyruleField"] },
    {"name": "土遁の術で敵を倒す", "en": "Defeat an enemy with Earthwake", "types": [ "GerudoHighlands", "HyruleField", "Yiga", "Travel"] },
    {"name": "コーガを3回倒す", "en": "Defeat Kohga Three Times", "types": [ "Combat", "Depths"] },
    {"name": "ミニチャレンジ/エピソードチャレンジ15つ", "en": "Complete 15 Side Quests/Adventures", "types": [ "SideQuests"] },
    {"name": "思い出の服", "en": "Tunic of Memories", "types": [ "Depths", "Armor"] },
    {"name": "エピソードチャレンジ:僕だけの魔物コレクション5", "en": "A Monsterous Collection V SA", "types": [ "Koltin", "Camera", "Gleeok"] },
    ], [
    {"name": "フリザゲイラをダイビングのみで倒す", "en": "Defeat Wind Temple Boss by only Skydiving", "types": [ "Combat", "Temples", "RosproPass"] },
    {"name": "ボルドゴーマをユン坊を使わず倒す", "en": "Defeat Fire Temple Boss without Yunobo's Ability", "types": [ "Combat", "Temples", "EldinCanyon"] },
    {"name": "オクタコスをシドを使わず倒す", "en": "Defeat Water Temple Boss without Sidon's Ability", "types": [ "Combat", "Temples", "UplandZorana"] },
    {"name": "雷の神殿をトーレルーフなしでクリアする", "en": "Complete Lightning Temple without using Ascend", "types": [ "Combat", "Temples", "GerudoCanyon"] },
    {"name": "英傑武器", "en": "Obtain a Champion's Weapon", "types": [ "Weapons", "Temples"] },
    {"name": "エピソードチャレンジ:数多の龍に見守られしフクロウ", "en": "The Owl Protected by Dragons SA", "types": [ "Temples", "RosproPass", "ThyphloRuins"] },
    {"name": "エピソードチャレンジ:二つの龍の狭間", "en": "The Corridor between Two Dragons SA", "types": [ "Temples", "EldinCanyon", "ThyphloRuins"] },
    {"name": "エピソードチャレンジ:六つの龍の御前", "en": "The Six Dragons SA", "types": [ "Temples", "UplandZorana", "ThyphloRuins"] },
    {"name": "エピソードチャレンジ:長き体の守護龍", "en": "The Long Dragon SA", "types": [ "Temples", "GerudoCanyon", "ThyphloRuins"] },
    ], [
    {"name": "固い盟約", "en": "Obtain a Solemn Vow", "types": [ "Temples", "Sky"] },
    {"name": "破魔の根20つ解放", "en": "Activate 20 Lightroots", "types": [ "Depths"] },
    {"name": "馬宿の絵のミニチャレンジ3つ", "en": "Complete 3 Stable Picture Side Quests", "types": [ "SideQuests", "Stables", "Camera", "Travel"] },
    {"name": "龍の泪12つ", "en": "Collect 12 Dragon Tear Memories", "types": [ "Lindor'sBrow", "Tears"] },
    {"name": "コーガを4回倒す", "en": "Defeat Kohga Four Times", "types": [ "Combat", "Depths", "Yiga"] },
    {"name": "マスターソード", "en": "Obtain the Master Sword", "types": [ "Shrines", "Weapons"] },
    {"name": "エピソードチャレンジ:大発明！図鑑センサー", "en": "Presenting: Sensor +! SA", "types": [ "SideAdventures", "Camera", "Temples", "Travel"] },
    {"name": "ワープマーカー", "en": "Obtain Travel Medallion", "types": [ "Temples", "MountLanayru"] },
    {"name": "ゼルダの手を掴む", "en": "Grab Zelda's Hand", "types": [ "Combat"] },
    ]
    ];